/**
 * Redaction Collaboration Panel - Unit Tests
 * US-V2-031: Focused unit tests for collaboration functionality
 */

import { ThemeProvider } from '@mui/material/styles';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { RedactionCollaborationPanel } from '../../src/components/staff/InteractiveRedactionEditor/RedactionCollaborationPanel';
import {
  ApprovalRequest,
  CollaborationSession,
  CommentThread,
} from '../../src/components/staff/InteractiveRedactionEditor/types';
import { theme } from '../../src/theme';

const mockCommentThread: CommentThread = {
  id: 'thread-1',
  redactionId: 'redaction-1',
  recordId: 'record-1',
  fileName: 'test.pdf',
  comments: [
    {
      id: 'comment-1',
      threadId: 'thread-1',
      userId: 'user-1',
      userName: 'John Doe',
      message: 'This redaction looks correct.',
      timestamp: '2024-01-15T10:00:00Z',
      isSystem: false,
    },
    {
      id: 'comment-2',
      threadId: 'thread-1',
      userId: 'user-2',
      userName: 'Jane Smith',
      message: 'Agreed, approved.',
      timestamp: '2024-01-15T11:00:00Z',
      isSystem: false,
    },
  ],
  status: 'active' as const,
  createdAt: '2024-01-15T10:00:00Z',
  lastActivity: '2024-01-15T11:00:00Z',
  participants: ['user-1', 'user-2'],
};

const mockApprovalRequest: ApprovalRequest = {
  id: 'approval-1',
  redactionId: 'redaction-1',
  recordId: 'record-1',
  requestedBy: 'user-1',
  requestedByName: 'John Doe',
  reviewers: ['user-3'],
  reviewerNames: ['Mike Wilson'],
  status: 'pending' as const,
  priority: 'high' as const,
  reason: 'Contains sensitive personal information',
  requestedAt: '2024-01-15T09:00:00Z',
  dueDate: '2024-01-17T17:00:00Z',
  approvals: [],
  metadata: {
    redactionType: 'SSN',
    confidence: 95,
    autoGenerated: false,
  },
};

const mockSession: CollaborationSession = {
  id: 'session-1',
  recordId: 'record-1',
  fileName: 'test.pdf',
  participants: [
    {
      id: 'user-1',
      name: 'John Doe',
      role: 'staff',
      status: 'active',
      joinedAt: '2024-01-15T09:00:00Z',
      permissions: {
        canEdit: true,
        canComment: true,
        canApprove: false,
        canDelete: false,
      },
    },
    {
      id: 'user-2',
      name: 'Jane Smith',
      role: 'supervisor',
      status: 'active',
      joinedAt: '2024-01-15T09:30:00Z',
      permissions: {
        canEdit: true,
        canComment: true,
        canApprove: true,
        canDelete: true,
      },
    },
  ],
  commentThreads: [mockCommentThread],
  approvalRequests: [mockApprovalRequest],
  settings: {
    allowAnonymousComments: false,
    requireApprovalForDeletion: true,
    maxConcurrentEditors: 5,
  },
  createdAt: '2024-01-15T09:00:00Z',
  lastActivity: '2024-01-15T11:00:00Z',
};

const TestWrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <ThemeProvider theme={theme}>{children}</ThemeProvider>
);

describe('RedactionCollaborationPanel Unit Tests', () => {
  const defaultProps = {
    session: mockSession,
    currentUserId: 'user-1',
    onAddComment: jest.fn(),
    onUpdateComment: jest.fn(),
    onDeleteComment: jest.fn(),
    onRequestApproval: jest.fn(),
    onApproveRedaction: jest.fn(),
    onRejectRedaction: jest.fn(),
    onInviteUser: jest.fn(),
    onUpdatePermissions: jest.fn(),
    onLeaveSession: jest.fn(),
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Component Initialization', () => {
    it('should render collaboration panel', () => {
      render(<RedactionCollaborationPanel {...defaultProps} />, {
        wrapper: TestWrapper,
      });

      expect(screen.getByText(/collaboration/i)).toBeInTheDocument();
      expect(screen.getByText('2 participants')).toBeInTheDocument();
    });

    it('should display active participants', () => {
      render(<RedactionCollaborationPanel {...defaultProps} />, {
        wrapper: TestWrapper,
      });

      expect(screen.getByText('John Doe')).toBeInTheDocument();
      expect(screen.getByText('Jane Smith')).toBeInTheDocument();
    });

    it('should show user roles', () => {
      render(<RedactionCollaborationPanel {...defaultProps} />, {
        wrapper: TestWrapper,
      });

      expect(screen.getByText('staff')).toBeInTheDocument();
      expect(screen.getByText('supervisor')).toBeInTheDocument();
    });

    it('should handle empty session gracefully', () => {
      const emptySession: CollaborationSession = {
        ...mockSession,
        participants: [],
        commentThreads: [],
        approvalRequests: [],
      };

      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          session={emptySession}
        />,
        { wrapper: TestWrapper }
      );

      expect(screen.getByText('0 participants')).toBeInTheDocument();
      expect(screen.getByText(/no active discussions/i)).toBeInTheDocument();
    });
  });

  describe('Comment System', () => {
    beforeEach(() => {
      render(<RedactionCollaborationPanel {...defaultProps} />, {
        wrapper: TestWrapper,
      });
    });

    it('should display comment threads', () => {
      expect(
        screen.getByText('This redaction looks correct.')
      ).toBeInTheDocument();
      expect(screen.getByText('Agreed, approved.')).toBeInTheDocument();
    });

    it('should show comment timestamps', () => {
      expect(screen.getByText(/Jan 15, 2024, 10:00 AM/)).toBeInTheDocument();
      expect(screen.getByText(/Jan 15, 2024, 11:00 AM/)).toBeInTheDocument();
    });

    it('should show comment authors', () => {
      const comments = screen.getAllByTestId(/comment-/);
      expect(comments[0]).toHaveTextContent('John Doe');
      expect(comments[1]).toHaveTextContent('Jane Smith');
    });

    it('should show add comment button for users with permission', () => {
      expect(
        screen.getByRole('button', { name: /add comment/i })
      ).toBeInTheDocument();
    });

    it('should open comment input when add button is clicked', async () => {
      const addButton = screen.getByRole('button', { name: /add comment/i });
      await userEvent.click(addButton);

      expect(screen.getByPlaceholderText(/add a comment/i)).toBeInTheDocument();
      expect(
        screen.getByRole('button', { name: /post comment/i })
      ).toBeInTheDocument();
    });

    it('should call onAddComment when submitting new comment', async () => {
      const onAddComment = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          onAddComment={onAddComment}
        />,
        { wrapper: TestWrapper }
      );

      const addButton = screen.getByRole('button', { name: /add comment/i });
      await userEvent.click(addButton);

      const commentInput = screen.getByPlaceholderText(/add a comment/i);
      await userEvent.type(commentInput, 'New test comment');

      const postButton = screen.getByRole('button', { name: /post comment/i });
      await userEvent.click(postButton);

      expect(onAddComment).toHaveBeenCalledWith('thread-1', 'New test comment');
    });

    it('should show edit options for own comments', () => {
      // Mock as user-1 who owns the first comment
      const editButtons = screen.getAllByLabelText(/edit comment/i);
      expect(editButtons).toHaveLength(1); // Only one comment by current user
    });

    it('should call onUpdateComment when editing', async () => {
      const onUpdateComment = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          onUpdateComment={onUpdateComment}
        />,
        { wrapper: TestWrapper }
      );

      const editButton = screen.getByLabelText(/edit comment/i);
      await userEvent.click(editButton);

      const editInput = screen.getByDisplayValue(
        'This redaction looks correct.'
      );
      await userEvent.clear(editInput);
      await userEvent.type(editInput, 'Updated comment text');

      const saveButton = screen.getByRole('button', { name: /save/i });
      await userEvent.click(saveButton);

      expect(onUpdateComment).toHaveBeenCalledWith(
        'comment-1',
        'Updated comment text'
      );
    });

    it('should call onDeleteComment when deleting', async () => {
      const onDeleteComment = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          onDeleteComment={onDeleteComment}
        />,
        { wrapper: TestWrapper }
      );

      const deleteButton = screen.getByLabelText(/delete comment/i);
      await userEvent.click(deleteButton);

      // Should show confirmation dialog
      const confirmButton = screen.getByRole('button', {
        name: /confirm delete/i,
      });
      await userEvent.click(confirmButton);

      expect(onDeleteComment).toHaveBeenCalledWith('comment-1');
    });

    it('should not show edit/delete for other users comments', () => {
      // Second comment is by user-2, current user is user-1
      const comments = screen.getAllByTestId(/comment-/);
      const secondComment = comments[1];

      expect(
        secondComment.querySelector('button[aria-label*="edit"]')
      ).toBeNull();
      expect(
        secondComment.querySelector('button[aria-label*="delete"]')
      ).toBeNull();
    });
  });

  describe('Approval System', () => {
    beforeEach(() => {
      render(<RedactionCollaborationPanel {...defaultProps} />, {
        wrapper: TestWrapper,
      });
    });

    it('should display approval requests', () => {
      expect(screen.getByText(/approval request/i)).toBeInTheDocument();
      expect(
        screen.getByText('Contains sensitive personal information')
      ).toBeInTheDocument();
    });

    it('should show approval request details', () => {
      expect(screen.getByText('Requested by John Doe')).toBeInTheDocument();
      expect(screen.getByText('Reviewer: Mike Wilson')).toBeInTheDocument();
      expect(screen.getByText('High Priority')).toBeInTheDocument();
      expect(screen.getByText(/due.*Jan 17/i)).toBeInTheDocument();
    });

    it('should show request approval button for eligible users', () => {
      expect(
        screen.getByRole('button', { name: /request approval/i })
      ).toBeInTheDocument();
    });

    it('should open approval request dialog', async () => {
      const requestButton = screen.getByRole('button', {
        name: /request approval/i,
      });
      await userEvent.click(requestButton);

      expect(
        screen.getByText(/request redaction approval/i)
      ).toBeInTheDocument();
      expect(
        screen.getByPlaceholderText(/reason for approval/i)
      ).toBeInTheDocument();
    });

    it('should call onRequestApproval when submitting request', async () => {
      const onRequestApproval = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          onRequestApproval={onRequestApproval}
        />,
        { wrapper: TestWrapper }
      );

      const requestButton = screen.getByRole('button', {
        name: /request approval/i,
      });
      await userEvent.click(requestButton);

      const reasonInput = screen.getByPlaceholderText(/reason for approval/i);
      await userEvent.type(reasonInput, 'Contains PII');

      const submitButton = screen.getByRole('button', {
        name: /submit request/i,
      });
      await userEvent.click(submitButton);

      expect(onRequestApproval).toHaveBeenCalledWith(
        expect.objectContaining({
          reason: 'Contains PII',
          priority: 'medium',
        })
      );
    });

    it('should show approve/reject buttons for reviewers', () => {
      // Mock as user-3 who is a reviewer
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-3'
        />,
        { wrapper: TestWrapper }
      );

      expect(
        screen.getByRole('button', { name: /approve/i })
      ).toBeInTheDocument();
      expect(
        screen.getByRole('button', { name: /reject/i })
      ).toBeInTheDocument();
    });

    it('should call onApproveRedaction when approving', async () => {
      const onApproveRedaction = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-3'
          onApproveRedaction={onApproveRedaction}
        />,
        { wrapper: TestWrapper }
      );

      const approveButton = screen.getByRole('button', { name: /approve/i });
      await userEvent.click(approveButton);

      const confirmButton = screen.getByRole('button', {
        name: /confirm approval/i,
      });
      await userEvent.click(confirmButton);

      expect(onApproveRedaction).toHaveBeenCalledWith(
        'approval-1',
        expect.any(String)
      );
    });

    it('should call onRejectRedaction when rejecting', async () => {
      const onRejectRedaction = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-3'
          onRejectRedaction={onRejectRedaction}
        />,
        { wrapper: TestWrapper }
      );

      const rejectButton = screen.getByRole('button', { name: /reject/i });
      await userEvent.click(rejectButton);

      const reasonInput = screen.getByPlaceholderText(/reason for rejection/i);
      await userEvent.type(reasonInput, 'Insufficient redaction');

      const confirmButton = screen.getByRole('button', {
        name: /confirm rejection/i,
      });
      await userEvent.click(confirmButton);

      expect(onRejectRedaction).toHaveBeenCalledWith(
        'approval-1',
        'Insufficient redaction'
      );
    });
  });

  describe('Participant Management', () => {
    beforeEach(() => {
      render(<RedactionCollaborationPanel {...defaultProps} />, {
        wrapper: TestWrapper,
      });
    });

    it('should show participant list', () => {
      const participantsList = screen.getByRole('list', {
        name: /participants/i,
      });
      expect(participantsList).toBeInTheDocument();

      expect(screen.getByText('John Doe')).toBeInTheDocument();
      expect(screen.getByText('Jane Smith')).toBeInTheDocument();
    });

    it('should show participant status indicators', () => {
      expect(screen.getAllByTestId('active-indicator')).toHaveLength(2);
    });

    it('should show invite user button for supervisors', () => {
      // Switch to supervisor user
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-2'
        />,
        { wrapper: TestWrapper }
      );

      expect(
        screen.getByRole('button', { name: /invite user/i })
      ).toBeInTheDocument();
    });

    it('should open invite user dialog', async () => {
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-2'
        />,
        { wrapper: TestWrapper }
      );

      const inviteButton = screen.getByRole('button', { name: /invite user/i });
      await userEvent.click(inviteButton);

      expect(screen.getByText(/invite user to session/i)).toBeInTheDocument();
      expect(
        screen.getByPlaceholderText(/enter user email/i)
      ).toBeInTheDocument();
    });

    it('should call onInviteUser when inviting', async () => {
      const onInviteUser = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-2'
          onInviteUser={onInviteUser}
        />,
        { wrapper: TestWrapper }
      );

      const inviteButton = screen.getByRole('button', { name: /invite user/i });
      await userEvent.click(inviteButton);

      const emailInput = screen.getByPlaceholderText(/enter user email/i);
      await userEvent.type(emailInput, 'newuser@example.com');

      const sendButton = screen.getByRole('button', {
        name: /send invitation/i,
      });
      await userEvent.click(sendButton);

      expect(onInviteUser).toHaveBeenCalledWith(
        'newuser@example.com',
        expect.any(Object)
      );
    });

    it('should show permission settings for supervisors', async () => {
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-2'
        />,
        { wrapper: TestWrapper }
      );

      const settingsButton = screen.getByRole('button', {
        name: /participant settings/i,
      });
      await userEvent.click(settingsButton);

      expect(screen.getByText(/manage permissions/i)).toBeInTheDocument();
    });

    it('should call onUpdatePermissions when changing permissions', async () => {
      const onUpdatePermissions = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-2'
          onUpdatePermissions={onUpdatePermissions}
        />,
        { wrapper: TestWrapper }
      );

      const settingsButton = screen.getByRole('button', {
        name: /participant settings/i,
      });
      await userEvent.click(settingsButton);

      const approveCheckbox = screen.getByLabelText(/can approve/i);
      await userEvent.click(approveCheckbox);

      const saveButton = screen.getByRole('button', {
        name: /save permissions/i,
      });
      await userEvent.click(saveButton);

      expect(onUpdatePermissions).toHaveBeenCalledWith(
        'user-1',
        expect.objectContaining({
          canApprove: true,
        })
      );
    });
  });

  describe('Real-time Updates', () => {
    it('should show typing indicators', () => {
      const sessionWithTyping = {
        ...mockSession,
        participants: [
          ...mockSession.participants,
          {
            id: 'user-3',
            name: 'Bob Johnson',
            role: 'staff' as const,
            status: 'typing' as const,
            joinedAt: '2024-01-15T10:00:00Z',
            permissions: {
              canEdit: true,
              canComment: true,
              canApprove: false,
              canDelete: false,
            },
          },
        ],
      };

      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          session={sessionWithTyping}
        />,
        { wrapper: TestWrapper }
      );

      expect(screen.getByText(/bob johnson is typing/i)).toBeInTheDocument();
      expect(screen.getByTestId('typing-indicator')).toBeInTheDocument();
    });

    it('should handle session updates', async () => {
      const { rerender } = render(
        <RedactionCollaborationPanel {...defaultProps} />,
        { wrapper: TestWrapper }
      );

      // Add a new participant
      const updatedSession = {
        ...mockSession,
        participants: [
          ...mockSession.participants,
          {
            id: 'user-4',
            name: 'New User',
            role: 'staff' as const,
            status: 'active' as const,
            joinedAt: '2024-01-15T12:00:00Z',
            permissions: {
              canEdit: true,
              canComment: true,
              canApprove: false,
              canDelete: false,
            },
          },
        ],
      };

      rerender(
        <RedactionCollaborationPanel
          {...defaultProps}
          session={updatedSession}
        />
      );

      await waitFor(() => {
        expect(screen.getByText('3 participants')).toBeInTheDocument();
        expect(screen.getByText('New User')).toBeInTheDocument();
      });
    });

    it('should show activity feed', () => {
      render(
        <RedactionCollaborationPanel {...defaultProps} showActivity={true} />,
        { wrapper: TestWrapper }
      );

      expect(screen.getByText(/recent activity/i)).toBeInTheDocument();
      expect(
        screen.getByText(/john doe joined the session/i)
      ).toBeInTheDocument();
      expect(
        screen.getByText(/jane smith added a comment/i)
      ).toBeInTheDocument();
    });
  });

  describe('Session Controls', () => {
    it('should show leave session button', () => {
      render(<RedactionCollaborationPanel {...defaultProps} />, {
        wrapper: TestWrapper,
      });

      expect(
        screen.getByRole('button', { name: /leave session/i })
      ).toBeInTheDocument();
    });

    it('should call onLeaveSession when leaving', async () => {
      const onLeaveSession = jest.fn();
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          onLeaveSession={onLeaveSession}
        />,
        { wrapper: TestWrapper }
      );

      const leaveButton = screen.getByRole('button', {
        name: /leave session/i,
      });
      await userEvent.click(leaveButton);

      const confirmButton = screen.getByRole('button', {
        name: /confirm leave/i,
      });
      await userEvent.click(confirmButton);

      expect(onLeaveSession).toHaveBeenCalled();
    });

    it('should show session settings for supervisors', () => {
      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          currentUserId='user-2'
        />,
        { wrapper: TestWrapper }
      );

      expect(
        screen.getByRole('button', { name: /session settings/i })
      ).toBeInTheDocument();
    });
  });

  describe('Accessibility', () => {
    beforeEach(() => {
      render(<RedactionCollaborationPanel {...defaultProps} />, {
        wrapper: TestWrapper,
      });
    });

    it('should have proper ARIA labels', () => {
      expect(
        screen.getByRole('region', { name: /collaboration panel/i })
      ).toBeInTheDocument();
      expect(
        screen.getByRole('list', { name: /participants/i })
      ).toBeInTheDocument();
      expect(
        screen.getByRole('region', { name: /comments/i })
      ).toBeInTheDocument();
    });

    it('should support keyboard navigation in participant list', () => {
      const participants = screen.getAllByRole('listitem');

      participants[0].focus();
      expect(participants[0]).toHaveFocus();

      fireEvent.keyDown(participants[0], { key: 'ArrowDown' });
      expect(participants[1]).toHaveFocus();
    });

    it('should announce activity updates to screen readers', async () => {
      const liveRegion = screen.getByRole('status', {
        name: /activity updates/i,
      });
      expect(liveRegion).toHaveAttribute('aria-live', 'polite');
    });
  });

  describe('Error Handling', () => {
    it('should handle missing session gracefully', () => {
      const consoleSpy = jest
        .spyOn(console, 'error')
        .mockImplementation(() => {});

      render(
        <RedactionCollaborationPanel {...defaultProps} session={null as any} />,
        { wrapper: TestWrapper }
      );

      expect(
        screen.getByText(/no active collaboration session/i)
      ).toBeInTheDocument();

      consoleSpy.mockRestore();
    });

    it('should handle callback errors gracefully', async () => {
      const onAddComment = jest.fn(() => {
        throw new Error('Add comment error');
      });

      const consoleSpy = jest
        .spyOn(console, 'error')
        .mockImplementation(() => {});

      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          onAddComment={onAddComment}
        />,
        { wrapper: TestWrapper }
      );

      const addButton = screen.getByRole('button', { name: /add comment/i });
      await userEvent.click(addButton);

      const commentInput = screen.getByPlaceholderText(/add a comment/i);
      await userEvent.type(commentInput, 'Test comment');

      const postButton = screen.getByRole('button', { name: /post comment/i });

      // Should not crash when callback throws
      await userEvent.click(postButton);

      consoleSpy.mockRestore();
    });
  });

  describe('Performance', () => {
    it('should virtualize long comment threads', () => {
      const longCommentThread: CommentThread = {
        ...mockCommentThread,
        comments: Array.from({ length: 100 }, (_, i) => ({
          id: `comment-${i}`,
          threadId: 'thread-1',
          userId: `user-${i % 3}`,
          userName: `User ${i}`,
          message: `Comment ${i}`,
          timestamp: new Date(2024, 0, 15, 10, i).toISOString(),
          isSystem: false,
        })),
      };

      const sessionWithLongThread = {
        ...mockSession,
        commentThreads: [longCommentThread],
      };

      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          session={sessionWithLongThread}
        />,
        { wrapper: TestWrapper }
      );

      // Should not render all 100 comments at once
      const visibleComments = screen.getAllByTestId(/comment-/);
      expect(visibleComments.length).toBeLessThan(20);
    });

    it('should debounce typing indicators', async () => {
      const mockTypingCallback = jest.fn();

      render(
        <RedactionCollaborationPanel
          {...defaultProps}
          onUserTyping={mockTypingCallback}
        />,
        { wrapper: TestWrapper }
      );

      const addButton = screen.getByRole('button', { name: /add comment/i });
      await userEvent.click(addButton);

      const commentInput = screen.getByPlaceholderText(/add a comment/i);

      // Type rapidly
      await userEvent.type(commentInput, 'test');

      // Should debounce and only call once
      await waitFor(() => {
        expect(mockTypingCallback).toHaveBeenCalledTimes(1);
      });
    });
  });
});
